[theme]
primaryColor = "#17a2b8"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#2d3748"

[server]
maxUploadSize = 200
enableXsrfProtection = true

[browser]
gatherUsageStats = false 